SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE catalogo_areas;

INSERT INTO catalogo_areas (id_area, nombre_area) VALUES 
(1, 'COORDINACIÓN DE LA GESTIÓN INSTITUCIONAL SEDE GUAYAQUIL'),
(2, 'COORDINACIÓN DE LA GESTIÓN INSTITUCIONAL SEDE LOJA'),
(3, 'COORDINACIÓN DE LA GESTIÓN INSTITUCIONAL SEDE QUITO'),
(4, 'COORDINACIÓN DE LA GESTIÓN INSTITUCIONAL SEDE RIOBAMBA'),
(5, 'DIRECCIÓN ADMINISTRATIVA FINANCIERA'),
(6, 'DIRECCIÓN DE ADMINISTRACIÓN DE RECURSOS HUMANOS'),
(7, 'DIRECCIÓN DE ASESORÍA JURÍDICA'),
(8, 'DIRECCIÓN DE COMUNICACIÓN SOCIAL'),
(9, 'DIRECCIÓN DE ESTUDIOS, INVESTIGACIÓN Y DESARROLLO HIDROMETEOROLÓGICO'),
(10, 'DIRECCIÓN DE INFORMACIÓN HIDROMETEOROLÓGICA'),
(11, 'DIRECCIÓN DE LA RED DE OBSERVACIÓN HIDROMETEOROLÓGICA'),
(12, 'DIRECCIÓN DE LABORATORIOS DE CALIDAD DE AGUAS Y SEDIMENTOS'),
(13, 'DIRECCIÓN DE PLANIFICACIÓN'),
(14, 'DIRECCIÓN DE PRONÓSTICOS Y ALERTAS HIDROMETEOROLÓGICAS'),
(15, 'DIRECCIÓN EJECUTIVA'),
(16, 'DIRECCIÓN REGIONAL TÉCNICA HIDROMETEOROLÓGICA - MANABI'),
(17, 'DIRECCIÓN REGIONAL TÉCNICA HIDROMETEOROLÓGICA - NAPO'),
(18, 'DIRECCIÓN REGIONAL TÉCNICA HIDROMETEOROLÓGICA - PASTAZA'),
(19, 'DIRECCIÓN REGIONAL TÉCNICA HIDROMETEOROLÓGICA ESMERALDAS - MIRA'),
(20, 'DIRECCIÓN REGIONAL TÉCNICA HIDROMETEOROLÓGICA GUAYAS - GALAPAGOS'),
(21, 'DIRECCIÓN REGIONAL TÉCNICA HIDROMETEOROLÓGICA MORONA SANTIAGO');

SET FOREIGN_KEY_CHECKS = 1;
