SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE catalogo_areas;

INSERT INTO catalogo_areas (id_area, nombre_area) VALUES 
(1, 'TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIÓN'),
(2, 'DIRECCIÓN DE INFORMACIÓN HIDROMETEOROLÓGICA'),
(3, 'DIRECCIÓN DE ADMINISTRACIÓN DE RECURSOS HUMANOS'),
(4, 'DIRECCIÓN ADMINISTRATIVA FINANCIERA'),
(5, 'DIRECCIÓN EJECUTIVA'),
(6, 'DIRECCIÓN DE ASESORÍA JURÍDICA'),
(7, 'DIRECCIÓN DE COMUNICACIÓN SOCIAL'),
(8, 'DIRECCIÓN DE PLANIFICACIÓN'),
(9, 'DIRECCIÓN DE PRONÓSTICOS Y ALERTAS'),
(10, 'DIRECCIÓN DE ESTUDIOS, INVESTIGACIÓN Y DESARROLLO HIDROMETEOROLÓGICO'),
(11, 'DIRECCIÓN DE LA RED NACIONAL DE OBSERVACIÓN HIDROMETEOROLÓGICA'),
(12, 'LABORATORIO NACIONAL DE CALIDAD DE AGUA Y SEDIMENTOS');

SET FOREIGN_KEY_CHECKS = 1;
